### ISSUE TITLE
Loading widget... and/or Error displaying widget: model not found

### ISSUE THREAD

**Issue by LuisFRoch** [bloomberg/bqplot#884]
Hi, I've encounter an error on bqplot after updating widegts. Figure/table widgets work as expected; however, bqplot only works in _voila preview and when using regular notebook_. In JLab i either get a never ending loading or error displaying widget. I've tried uninstalling/re-installing bqplot, jupyterlab manager, testing sliders (some work), etc... Any ideas what it could be?
I have the following configurations:
Any help appreciated. Thanks!

```
JupyterLab v1.0.2
Known labextensions:
   app dir: /Users/Me/miniconda3/envs/JupyterProjects/share/jupyter/lab
        @jupyter-voila/jupyterlab-preview v0.1.0  enabled  OK
        @jupyter-widgets/jupyterlab-manager v1.0.1  enabled  OK
        bqplot v0.5.0-alpha.2  enabled  OK
        jupyterlab-chart-editor v1.2.0  enabled  OK
        jupyterlab-plotly v1.0.0  enabled  OK
        plotlywidget v1.0.0  enabled  OK

```
```
Error displaying: 
manager.js:251 Uncaught (in promise) Error: Module bqplot, semver range ^0.4.6 is not registered as a widget module
    at WidgetManager.loadClass (manager.js:251)
    at WidgetManager.<anonymous> (manager-base.js:263)
    at step (manager-base.js:44)
    at Object.next (manager-base.js:25)
    at manager-base.js:19
    at new Promise (<anonymous>)
    at push.hs2k.__awaiter (manager-base.js:15)
    at WidgetManager.push.hs2k.ManagerBase._make_model (manager-base.js:257)
    at WidgetManager.<anonymous> (manager-base.js:246)
    at step (manager-base.js:44)
```
<img width="587" alt="Screen Shot 2019-07-28 at 3 51 53 PM" src="https://user-images.githubusercontent.com/29665541/62007599-bb096a80-b14f-11e9-87c5-79795aac27bf.png">

**Comment by tslaton** [comment]
I did some introspection on `jupyterlab-manager` (1.0.2 in my case) and found it was looking for `'0.5.0-alpha.2'`.

In the install of bqplot I got by doing `pip install bqplot`, my `__frontend_version__` was `'^0.4.6'` however, and I was seeing the same error reported above. Changing it within the locally installed `_version.py`  to `'^0.5.0-alpha.2'` got me past the error, which is interesting because the `master` branch already has this `__frontend_version__` properly set [here](https://github.com/bloomberg/bqplot/blob/master/bqplot/_version.py#L8).

**Comment by tslaton** [comment]
That's only lead me to a new error, though, trying to execute the second cell in the image example [here](https://github.com/bloomberg/bqplot/blob/master/examples/Marks/Object%20Model/Image.ipynb). I think the pip release of bqplot might not be compatible with JupyterLab ^1.0.0 yet.

For what it's worth, the error I'm now seeing is:

```
[Error] not sure what the data is
	deserialize_array_or_json (vendors~main.f1b615f707322c40d5c5.js:354557)
	_deserialize_state (vendors~main.f1b615f707322c40d5c5.js:416274)
	(anonymous function) (vendors~main.f1b615f707322c40d5c5.js:350863)
	step (vendors~main.f1b615f707322c40d5c5.js:350628)
	fulfilled (vendors~main.f1b615f707322c40d5c5.js:350600)
	promiseReactionJob
```

**Comment by tslaton** [comment]
Installing `bqplot` from `master` works for me, as I am just trying to build a prototype right now anyway:

```
pip install -e git+git://github.com/bloomberg/bqplot.git@master#egg=bqplot
```

If you're relying on any kind of stability though, you might want to wait for a release.

**Comment by LuisFRoch** [comment]
I'll try the install from master. Thanks @tslaton for the tips!

**Comment by juangesino** [comment]
Thanks @tslaton, installing from master solved the issue for me

**Comment by LuisFRoch** [comment]
> I'll try the install from master. Thanks @tslaton for the tips!

Fixed. Thanks @tslaton

**Comment by oronimbus** [comment]
I have the same issue - some of bqplot (except pyplot) works in Jupyter Notebook but not in JLab. Having followed `pip install -e git+git://github.com/bloomberg/bqplot.git@master#egg=bqplot
` I get the below error message: 

![Screen Shot 2019-08-04 at 14 56 29](https://user-images.githubusercontent.com/11311783/62424574-522e6f00-b6c8-11e9-91ef-061d788238ec.png)

```
JupyterLab v1.0.4
Known labextensions:
   app dir: /usr/local/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.0.2  enabled  OK
        @jupyterlab/git v0.7.0  enabled  OK
        bqplot v0.5.0-alpha.2  enabled  OK
```

Am I doing something wrong?

**Comment by LuisFRoch** [comment]
@oronimbus I would try installing on a clean env.

**Comment by oronimbus** [comment]
FYI I just fixed this issue on my side using `sudo jupyter labextension install bqplot@0.4.6`. Bqplot charts now correctly display in both JL and JNB. This was suggested in #885 . Thanks!

**Comment by AurelieGiraud1** [comment]
Thanks @oronimbus ! it also works for me like that.

**Comment by DaliDalmas** [comment]
You are a saviour @oronimbus

**Comment by Serhiy-Shekhovtsov** [comment]
I run all of these, and it's still not working:

```
pip install bqplot==0.11.6
jupyter labextension install bqplot@0.4.6
jupyter lab build
```

Tried the same with *.6, same thing.
